const data = window.SITE_CONTENT;
const $ = id => document.getElementById(id);
const el = (tag, text, cls) => { const n=document.createElement(tag); if(text != null)n.textContent=text;if(cls)n.className=cls;return n; };
const safeUrl = value => {try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}};
const link = (text,url,cls) => {const a=el('a',text,cls);a.href=url;return a;};
$('name').textContent=data.name;$('role').textContent=data.role;$('headline').textContent=data.headline;$('intro').textContent=data.intro;$('about').textContent=data.about;$('demo-note').hidden=!data.demo;document.title=data.name+' · AI 与机器人人才招聘';
document.querySelector('meta[name="description"]').content=data.intro;
$('copyright').textContent='© '+new Date().getFullYear()+' '+data.name;
data.directions.forEach((d,i)=>{const card=el('article',null,'direction');card.append(el('span',String(i+1).padStart(2,'0'),'number'),el('h3',d.title),el('div',d.english,'english'),el('p',d.description));const tags=el('div');d.tags.forEach(t=>tags.append(el('span',t,'tag')));card.append(tags);$('directions').append(card);});
const dialog=$('detail');let lastTrigger;
function showDetail(title,meta,body,requirements,url){lastTrigger=document.activeElement;const root=$('detail-content');root.replaceChildren(el('p',meta,'eyebrow'),el('h2',title),el('p',body));if(requirements?.length){const list=el('ul');requirements.forEach(r=>list.append(el('li',r)));root.append(list);}if(safeUrl(url))root.append(link('查看完整信息 ↗',safeUrl(url),'button'));else if(data.email){root.append(link('联系 James ↗','mailto:'+data.email+'?subject='+encodeURIComponent(title),'button'));}dialog.showModal();}
$('close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>lastTrigger?.focus());dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close();});
let category='全部';const categories=['全部',...new Set(data.jobs.map(j=>j.category))];
categories.forEach(c=>{const b=el('button',c,'filter'+(c===category?' active':''));b.setAttribute('aria-pressed',String(c===category));b.addEventListener('click',()=>{category=c;[...$('filters').children].forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});renderJobs();});$('filters').append(b);});
function renderJobs(){const query=$('search').value.trim().toLowerCase();const jobs=data.jobs.filter(j=>(category==='全部'||j.category===category)&&[j.title,j.location,j.category].join(' ').toLowerCase().includes(query));$('jobs').replaceChildren();$('job-count').textContent=jobs.length+' 个岗位方向 · 具体招聘状态以沟通为准';jobs.forEach(j=>{const row=el('article',null,'job');const info=el('div');info.append(el('h3',j.title),el('p',[j.category,j.location,j.type].filter(Boolean).join(' / ')));const b=el('button','了解岗位 ↗');b.setAttribute('aria-label','了解'+j.title);b.addEventListener('click',()=>showDetail(j.title,j.status+' / '+j.category,j.summary,j.requirements,j.url));row.append(info,el('span',j.status,'job-status'),b);$('jobs').append(row);});if(!jobs.length)$('jobs').append(el('p','暂时没有匹配的职位，试试其他关键词或方向。','empty'));}
$('search').addEventListener('input',renderJobs);renderJobs();
data.posts.forEach(p=>{const card=el('article',null,'post');card.append(el('div',[p.category,p.date].filter(Boolean).join(' / '),'post-meta'),el('h3',p.title),el('p',p.excerpt));if(safeUrl(p.url))card.append(link('阅读全文 ↗',safeUrl(p.url)));else{const b=el('button','阅读记录 ↗');b.addEventListener('click',()=>showDetail(p.title,p.category,p.body));card.append(b);}$('posts').append(card);});
if(!data.posts.length)$('posts').append(el('p','第一篇观察，正在酝酿。','empty'));
if(data.email)$('contact-links').append(link('邮件联系 ↗','mailto:'+data.email));if(safeUrl(data.linkedin))$('contact-links').append(link('LinkedIn ↗',safeUrl(data.linkedin)));if(safeUrl(data.github))$('contact-links').append(link('GitHub ↗',safeUrl(data.github)));if(data.wechat)$('contact-links').append(el('p','微信：'+data.wechat,'pending'));if(!data.email&&!data.linkedin&&!data.wechat)$('contact-links').append(el('p','更多联系方式待补充','pending'));
